// Verified against the official portals on 25 September 2026. Listings are
// discovery links; scheme eligibility and application windows belong to the portals.
const maha = 'https://mahadbt.maharashtra.gov.in/SchemeData/SchemeData?str=';
const tribal = 'https://dbttribal.gov.in/AllScheme.aspx';
export const schemes = [
  { name: 'Post Matric Scholarship Scheme (Government of India)', provider: 'MahaDBT · Maharashtra', level: 'Post matric', summary: 'ST students studying after Class 10 in Maharashtra; income and course conditions apply.', url: maha + 'E9DDFA703C38E51A668ED132B54E2162E54C475F826D85C79DA948301E5F7772' },
  { name: 'Tuition Fee & Exam Fee for Tribal Students (Freeship)', provider: 'MahaDBT · Maharashtra', level: 'Post matric', summary: 'Tuition and examination fee support for eligible ST students in Maharashtra.', url: maha + 'E9DDFA703C38E51AE7C10C1B9446574716EB93196C4CB29808753F77C61BEF29' },
  { name: 'Vocational Education Fee Reimbursement', provider: 'MahaDBT · Maharashtra', level: 'Vocational', summary: 'Fee reimbursement for eligible ST students enrolled in vocational education.', url: maha + 'E9DDFA703C38E51A903EC510F2DCBF009D17A0AB763F0C2343B13AF0AB323366' },
  { name: 'Vocational Education Maintenance Allowance', provider: 'MahaDBT · Maharashtra', level: 'Vocational', summary: 'Maintenance support for eligible ST students in vocational courses.', url: maha + 'E9DDFA703C38E51A150D8D3BD5BBF9E579F0BA8D2D926043D82C17776CB73469' },
  { name: 'Vocational Training Fee Reimbursement for ST Students', provider: 'MahaDBT · Maharashtra', level: 'Vocational', summary: 'Training fee reimbursement for eligible Scheduled Tribe students.', url: maha + 'E9DDFA703C38E51A1CE86EBA1BA63DA13D68304CE1D46C55A5B53B49580C2589' },
  { name: 'Pre-Matric Scholarship Scheme for ST Students', provider: 'Ministry of Tribal Affairs · DBT', level: 'Pre matric', summary: 'Centrally sponsored school scholarship; follow your state application route.', url: tribal },
  { name: 'Post-Matric Scholarship Scheme for ST Students', provider: 'Ministry of Tribal Affairs · DBT', level: 'Post matric', summary: 'Centrally sponsored scholarship administered through state portals; also listed on MahaDBT for Maharashtra.', url: tribal },
  { name: 'Top Class Education for ST Students', provider: 'Ministry of Tribal Affairs · Central sector', level: 'Higher education', summary: 'Higher education scholarship for eligible ST students at notified institutions; check the current NSP listing.', url: 'https://scholarships.gov.in/All-Scholarships' },
  { name: 'National Fellowship for ST Students', provider: 'Ministry of Tribal Affairs · Central sector', level: 'Research', summary: 'Fellowship for eligible ST research scholars. The existing NFST form remains available above.', url: tribal },
  { name: 'National Overseas Scholarship Scheme', provider: 'Ministry of Tribal Affairs · Central sector', level: 'Overseas', summary: 'Support for eligible ST students studying abroad. The existing NOS form remains available above.', url: tribal },
  { name: 'PM-USP Central Sector Scholarship for College and University Students', provider: 'Ministry of Education · NSP', level: 'Higher education', summary: 'Merit-based national scholarship open to eligible students including ST applicants; check the NSP rules and current window.', url: 'https://scholarships.gov.in/All-Scholarships' },
];

// Concise bilingual summaries. Always confirm detailed eligibility on the linked portal.
const details = [
  ['दसवीं के बाद की छात्रवृत्ति (भारत सरकार)', 'महाराष्ट्र के अनुसूचित जनजाति विद्यार्थियों के लिए दसवीं के बाद पढ़ाई की सहायता।', 'Maharashtra ST students in eligible post-matric courses; income rules apply.', 'Scholarship and maintenance support according to course and residency.', 'पात्र पाठ्यक्रम में महाराष्ट्र के जनजातीय विद्यार्थी; आय संबंधी शर्तें लागू।', 'पाठ्यक्रम और निवास के अनुसार छात्रवृत्ति तथा निर्वाह सहायता।'],
  ['जनजातीय विद्यार्थियों के लिए शिक्षण व परीक्षा शुल्क छूट', 'महाराष्ट्र के पात्र जनजातीय विद्यार्थियों के शिक्षण और परीक्षा शुल्क में सहायता।', 'Eligible ST students studying in Maharashtra.', 'Tuition and examination fee support.', 'महाराष्ट्र में पढ़ने वाले पात्र जनजातीय विद्यार्थी।', 'शिक्षण और परीक्षा शुल्क में सहायता।'],
  ['व्यावसायिक शिक्षा शुल्क प्रतिपूर्ति', 'पात्र जनजातीय विद्यार्थियों के व्यावसायिक पाठ्यक्रम शुल्क की प्रतिपूर्ति।', 'Eligible ST students in vocational education.', 'Reimbursement of eligible course fees.', 'व्यावसायिक शिक्षा के पात्र जनजातीय विद्यार्थी।', 'पात्र पाठ्यक्रम शुल्क की प्रतिपूर्ति।'],
  ['व्यावसायिक शिक्षा निर्वाह भत्ता', 'व्यावसायिक पाठ्यक्रम में पढ़ रहे पात्र विद्यार्थियों के निर्वाह खर्च की सहायता।', 'Eligible ST students in vocational education.', 'Maintenance allowance subject to scheme conditions.', 'व्यावसायिक शिक्षा के पात्र जनजातीय विद्यार्थी।', 'योजना की शर्तों के अनुसार निर्वाह भत्ता।'],
  ['जनजातीय विद्यार्थियों के लिए व्यावसायिक प्रशिक्षण शुल्क प्रतिपूर्ति', 'पात्र जनजातीय विद्यार्थियों के प्रशिक्षण शुल्क की प्रतिपूर्ति।', 'Eligible ST students in vocational training.', 'Reimbursement of eligible training fees.', 'व्यावसायिक प्रशिक्षण के पात्र जनजातीय विद्यार्थी।', 'पात्र प्रशिक्षण शुल्क की प्रतिपूर्ति।'],
  ['स्कूल स्तर की जनजातीय छात्रवृत्ति', 'स्कूल में पढ़ने वाले पात्र जनजातीय विद्यार्थियों के लिए केंद्र प्रायोजित योजना।', 'ST school students meeting their state scheme conditions.', 'Pre-matric scholarship through the state application route.', 'राज्य की शर्तें पूरी करने वाले स्कूल स्तर के जनजातीय विद्यार्थी।', 'राज्य के आवेदन माध्यम से स्कूल स्तर की छात्रवृत्ति।'],
  ['दसवीं के बाद की जनजातीय छात्रवृत्ति', 'दसवीं के बाद पात्र जनजातीय विद्यार्थियों के लिए केंद्र प्रायोजित सहायता।', 'ST students in eligible post-matric study; state rules apply.', 'Post-matric support administered through state portals.', 'दसवीं के बाद पात्र जनजातीय विद्यार्थी; राज्य की शर्तें लागू।', 'राज्य पोर्टल के माध्यम से छात्रवृत्ति सहायता।'],
  ['जनजातीय विद्यार्थियों के लिए उच्च शिक्षा छात्रवृत्ति', 'अधिसूचित संस्थानों में पढ़ने वाले पात्र जनजातीय विद्यार्थियों के लिए केंद्र की योजना।', 'Eligible ST students at notified institutions.', 'Higher education scholarship per current NSP guidelines.', 'अधिसूचित संस्थानों में पढ़ने वाले पात्र जनजातीय विद्यार्थी।', 'एनएसपी के वर्तमान दिशानिर्देशों के अनुसार उच्च शिक्षा सहायता।'],
  ['राष्ट्रीय जनजातीय अध्येतावृत्ति', 'पात्र जनजातीय शोध विद्यार्थियों के लिए अध्येतावृत्ति।', 'Eligible ST research scholars.', 'Research fellowship per current ministry guidelines.', 'पात्र जनजातीय शोध विद्यार्थी।', 'मंत्रालय के वर्तमान नियमों के अनुसार शोध अध्येतावृत्ति।'],
  ['राष्ट्रीय विदेश छात्रवृत्ति', 'विदेश में उच्च शिक्षा के लिए पात्र जनजातीय विद्यार्थियों की सहायता।', 'Eligible ST students pursuing study abroad.', 'Overseas study support per current ministry guidelines.', 'विदेश में पढ़ाई करने वाले पात्र जनजातीय विद्यार्थी।', 'मंत्रालय के वर्तमान नियमों के अनुसार विदेश अध्ययन सहायता।'],
  ['पीएम-यूएसपी केंद्रीय क्षेत्र महाविद्यालय छात्रवृत्ति', 'पात्र महाविद्यालय विद्यार्थियों के लिए योग्यता आधारित राष्ट्रीय योजना।', 'Meritorious college students meeting NSP eligibility, including eligible ST students.', 'College or university scholarship per current NSP guidelines.', 'एनएसपी की पात्रता पूरी करने वाले महाविद्यालय विद्यार्थी, जिनमें जनजातीय विद्यार्थी भी शामिल हैं।', 'एनएसपी के वर्तमान नियमों के अनुसार छात्रवृत्ति।'],
];
schemes.forEach((scheme, index) => {
  const [nameHi, summaryHi, eligibility, benefit, eligibilityHi, benefitHi] = details[index];
  Object.assign(scheme, { nameHi, summaryHi, eligibility, benefit, eligibilityHi, benefitHi });
});
